### ISSUE TITLE
s_client refusing -connect - On older Debian (GLIBC 2.13)

### ISSUE THREAD

**Issue by Quix0r** [mozilla/cipherscan#127]
The said message comes with Debian:
````
$ ./cipherscan www.somehost.example
/home/user/git/cipherscan/openssl s_client doesn't accept the -connect parameter, which is extremely strange; refusing to proceed.
$ ./openssl
./openssl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./openssl)
./openssl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./openssl)
$
````
Or maybe (better!) reconsider rewrititing it and avoid binary blobs (which may not run on all Linux distributions).

**Comment by jvehent** [comment]
Use your system's openssl: `$ ./cipherscan -o $(which openssl) google.com`

But be aware the results will only be as good as what your distribution's openssl supports.

Unfortunately, there's no magic bullet to run cipherscan on older distribution. The solution here is to run something newer.

**Comment by tomato42** [comment]
> Or maybe (better!) reconsider rewrititing it and avoid binary blobs (which may not run on all Linux distributions).

we are well aware of this and it's in the works

**Comment by Quix0r** [comment]
Okay.
