### ISSUE TITLE
Print the ip adress

### ISSUE THREAD

**Issue by david-richer-adsk** [mozilla/cipherscan#130]
Is it possible to print the ip address of the server that cipherscan is talking to?
I tried with -v with no success.  

I am trying to diagnose an issue where dns return different servers with tls/ssl not the same across the board.

Thanks for this piece of software!

**Comment by jvehent** [comment]
Seems unlikely. The DNS resolution is handled by openssl and I don't
believe it exposes it to the calling script.

**Comment by david-richer-adsk** [comment]
My workaround was to ping the server to get an ip and add a temporary entry in my local /etc/host.

**Comment by tomato42** [comment]
if you want to scan an IP not a hostname, you can resolve its name using `host` and then specify the hostname (for SNI) manually:
```
./cipherscan -servername google.com 216.58.214.238:443
```

**Comment by david-richer-adsk** [comment]
Thanks for the tip, lot simpler!
