### ISSUE TITLE
Add documentation how to properly install or use custom OpenSSL version

### ISSUE THREAD

**Issue by Franky1** [mozilla/cipherscan#185]
I refer to the section **OpenSSL** in the README.md
- Is this custom OpenSSL version still required?
- If i follow the link to the other github repo, it seems to be not maintained anymore?
- Will the systems default openssl version work too?

If this *custom* OpenSSL version is still required:
Maybe it is a no brainer for experienced Linux users, but please add or fix the install description in the section **OpenSSL**
I tried it in a fresh Ubuntu 18.04 in Virtualbox, but couldn't get this to work properly.
Some dependencies are missing?
```
sudo apt-get install build-essential --yes
sudo apt-get install libz-dev --yes
```
And after running the installation commands `openssl version -a` still points to the default openssl version that was pre-installed on the system.

**Comment by tomato42** [comment]
> Is this custom OpenSSL version still required?

yes

> If i follow the link to the other github repo, it seems to be not maintained anymore?

it's not so much unmaintained as it's hard to move to 1.1.x branch

> Will the systems default openssl version work too?

yes, but then it won't show support for ciphers unsupported by systems' default openssl version

see also: #165 and #118

> Maybe it is a no brainer for experienced Linux users, but please add or fix the install description in the section OpenSSL
> I tried it in a fresh Ubuntu 18.04 in Virtualbox, but couldn't get this to work properly.
> Some dependencies are missing?

there's an already-compiled copy included in this repo, use it

> And after running the installation commands openssl version -a still points to the default openssl version that was pre-installed on the system.

you absolutely shouldn't install the custom openssl system-wide, you should build it statically and use that statically-built binary, if you have problems compiling it, please refer to its documentation
