### ISSUE TITLE
Cipherscan working on termux

### ISSUE THREAD

**Issue by enigm4s** [mozilla/cipherscan#186]
Hi, I just want to tell you if Cipherscan is working on this little device of mine. I was walking around github to see if there's some tool I can try, the a little curious inside me tried this tool. It was error at firts time because tlslite and ecdsa wont install corectly so I have to install it manually.

well, after some google around :
because it is running on termux android environment, I have to manually fix shebang using termux-fix-shebang on cscan.sh, cscan.py, analyze.py. Cipherscan /dev/stdout on line 529 shows error, giving me blank screen (fix it with change it to /proc/self/fd/1 )

On the cscan.py start line 255, I have IndexError: index out of range,  line 256 giving the host, port and hostname variable not defined. the fix is just push some indentation and its worked.
here's the result :

```
...
hostname = None
    if len(args) == 2:
        hostname = args[1]
        hostaddr = args[0].split(":")
        if len(hostaddr) > 1:
            host, port = hostaddr
        else:
            host = hostaddr[0]
            port = 443
            if run_probe:
                single_probe(run_probe)
            else:
                scan_TLS_intolerancies(host, port, hostname)
```

![Screenshot_20200716-064444](https://user-images.githubusercontent.com/68355570/87610882-ca9f0c00-c730-11ea-93b6-db39c11f39e5.png)

note: if this fix is wrong, you can show me the good trick :)
sudo ./cipherscan giving the output like it was intended:

![Screenshot_20200716-063052](https://user-images.githubusercontent.com/68355570/87609927-14d2be00-c72e-11ea-8e5f-a8f857de7060.png)
![Screenshot_20200716-063107](https://user-images.githubusercontent.com/68355570/87609943-21571680-c72e-11ea-9b98-97af168525e9.png)

I don't know why it shows different output (like the certificate explanation, trusted or something), but I'm happy because this tool is working on my mini beast. Atleast, I don't have to open decoder[dot]link for a while.

That's all, I'm not a programmer nor a developer, just a curious user, thanks for this awesome tool :)

**Comment by tomato42** [comment]
those changes to cscan.py suggest that the way it's called is incorrect: the hostname and or port is not passed in

**Comment by enigm4s** [comment]
> those changes to cscan.py suggest that the way it's called is incorrect: the hostname and or port is not passed in

Hi, I've managed to get some info about the host, just change indentation back.

starting from line 256, if run_probe:

![Screenshot_20200716-184011](https://user-images.githubusercontent.com/68355570/87667068-ee476e00-c793-11ea-882e-7c9218bdbd41.png)
![Screenshot_20200716-184318](https://user-images.githubusercontent.com/68355570/87667271-41b9bc00-c794-11ea-9c5c-98fdab3aa05a.png)

it just kinda scary when using vertical screen mode, but nevermind, its cool !

**Comment by enigm4s** [comment]
I forgot to closed this, keep the cool work dev :D
